apiVersion: app/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 5
  selector:
    matchLabels:
      name: task
  template:
    metadata:
      labels:
        name: task
    spec:
      containers:
      - name: application
        image: vashishti/task
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000